### ISSUE TITLE
blank web pages

### ISSUE THREAD

**Issue by mark-hahn** [mark-hahn/web-browser#12]
Sometimes when going back to an old webpage by clicking on its tab, it appears blank (white).  I haven't yet figured out what sequence of operations causes this.

**Comment by mark-hahn** [comment]
I can repeat this now ...

- open one text file in one pane
- add webpage to that pane
- select text file and split right
- select original text file again
- select web page tab

Then the webpage shows a reload indicator and comes up all white.  That tab never works again.

**Comment by mark-hahn** [comment]
See https://github.com/atom/atom-shell/issues/1110

**Comment by Ajedi32** [comment]
Can confirm that I've noticed this bug.

Also, I've seen it happen sometimes just when switching between tabs, though I can't reproduce the problem consistently using that approach.

**Comment by mark-hahn** [comment]
> Can confirm that I've noticed this bug.

I've seen it in different situations but luckily I found the repeatable case.

FWIW, you can fix the blank page by doing a small resize of the window.

**Comment by mark-hahn** [comment]
It's been a month and I haven't seen it again.  Have you?

**Comment by mark-hahn** [comment]
This web-browser package is no longer supported.  Use the atom package browser-plus instead.
