### ISSUE TITLE
"Cannot read property 'setFaviconDomain' of undefined"

### ISSUE THREAD

**Issue by Xety** [mark-hahn/web-browser#2]
Hello,
First, your plugin is so awesome, i was so tired to navigate between Chrome and Atom... :smile: 

But, i have an error to load the page when i press the key "Enter". 
The page is loaded after 10/15secondes, but after all work well when i navigate on the site.
![ma3qyoo](https://cloud.githubusercontent.com/assets/8210023/4711355/5fe65a26-58b9-11e4-8599-d1660c08dadb.png)

Atom : 0.138.0
Windows : 8.1

**Comment by mark-hahn** [comment]
fixed in 1.0.0
