### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isLoading' of undefined

### ISSUE THREAD

**Issue by Ajedi32** [mark-hahn/web-browser#28]
Just updated to v1.1.2. (Though truthfully I hadn't used this package much prior to this version.) Now I'm getting an error while trying to open a local file with this package. Auto generated bug report from Atom is displayed below.

---

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1
**Thrown From**: [web-browser](https://github.com/mark-hahn/web-browser) package, v1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'isLoading' of undefined

```
At C:\Users\Ajedi32\AppData\Local\atom\app-0.177.0\resources\atom\renderer\lib\web-view\web-view.js:282

TypeError: Cannot read property 'isLoading' of undefined
  at webview.isLoading (C:\Users\Ajedi32\AppData\Local\atom\app-0.177.0\resources\atom\renderer\lib\web-view\web-view.js:282:77)
  at C:\Users\Ajedi32\.atom\packages\web-browser\lib\page-view.coffee:34:29

```

### Commands

```
     -0:37.5 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:34.3 core:confirm (atom-text-editor.editor.mini)
     -0:34.3 web-browser:toggle (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "preview-plus",
      "browser-refresh"
    ]
  }
}
```

### Installed Packages

```coffee
# User
css-snippets, v0.5.0
html-helper, v0.2.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-javac, v0.1.3
web-browser, v1.1.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by mark-hahn** [comment]
Thanks mucho for the report.  The specific error you show if fixed in 1.1.3 which has just been released.

Can you tell me how you were trying to use it?  How were you serving the file and what URL did you use?

**Comment by Ajedi32** [comment]
I was just opening the file locally. (E.g. with the `file://` protocol.)

URL was along the lines of: `file:///C:/Users/Ajedi32/Documents/Ajedi32/Education/College%20Notes/Spring%202015/Advanced%20Web%20Design/CSS%20Review%20Assignment/assignment_2/css_review_assignment.html`

**Comment by Ajedi32** [comment]
Oh, and just to confirm, that commit did fix my problem.

**Comment by mark-hahn** [comment]
Thanks very much for the reporting. 

I would appreciate any feedback on how this auto-reload feature works when developing real web apps.  I can't tell in my testing whether it is useful or not.

**Comment by Ajedi32** [comment]
I suspect this feature will be really useful for my use case, but I'm not exactly developing a "real web app", I'm just building some simple web pages for a class in college. I do perform real web development work at my job, but I can't get Atom on my machine there due to it being a 32-bit Ubuntu installation.
