### ISSUE TITLE
Browser buttons don't respond to clicks

### ISSUE THREAD

**Issue by Ajedi32** [mark-hahn/web-browser#29]
I was trying to test out the fix to #4, but the auto refresh button didn't seem to do anything when I clicked it. Upon further investigation, I noticed that none of the browser buttons seem to be responding to my clicks. (The menu, refresh, and back buttons don't do anything when I click them.)

The only button that seems to respond to my clicks is the globe itself in the upper-left, which responds by hiding the url bar.

In-page buttons are not affected by this bug.

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1

**Comment by mark-hahn** [comment]
That is *really* broken.  Will fix right now.  I have got to get some spec
tests going.

**Comment by mark-hahn** [comment]
fixed in 1.1.4

Sorry and thanks.  I released it with a bunch of important commented out for debugging.

**Comment by Ajedi32** [comment]
Stuff was commented out? Ha. That's a new one for me. :smirk:

Yeah, some tests (and maybe a Travis build) would probably be helpful at this point. :laughing:
