### ISSUE TITLE
Refreshing a local page loads about:blank

### ISSUE THREAD

**Issue by Ajedi32** [mark-hahn/web-browser#31]
When a page is open in a `web-browser` tab and I click refresh or a refresh is triggered by the auto-reload feature, the page refreshes, but it loads `about:blank` instead of the page it was originally displaying.

This only seems to occur when the tab is displaying a local page (with the `file://` protocol), and not when the page being refreshed is live on the web.

**Comment by mark-hahn** [comment]
I have repeated this and it appears to be a bug in the webview tag in atom/shell.

https://github.com/atom/atom-shell/issues/1116

**Comment by mark-hahn** [comment]
1.1.8 has a workaround for this bug.  Auto-reload and reload now always reload the original URL from when the auto-reload flag was set on the tab.  This should make the auto-reload feature useful for local (non served) files.

One bad behavior is still there from this webview bug ...

- Load a local `file://` web page
- Click on a link to a remote web page
- hit the back button

The page will be right but then a manual reload will take you back to the remote page.  This isn't as big a problem as the original symptom.

Everything about local files will be fixed when the webview bug is fixed.

**Comment by Ajedi32** [comment]
Yeah, that seems like it should work fine for my purposes. Thanks for your help! :+1:
