### ISSUE TITLE
URL doesn't get updated by HTML5 history operations

### ISSUE THREAD

**Issue by wmertens** [mark-hahn/web-browser#35]
When e.g. working on a revealjs document, the current slide is encoded in the URL. However, this doesn't get updated in the web-browser it seems, because if you reload it switches back to the beginning.

**Comment by mark-hahn** [comment]
Can you please give me a quick set of steps to reproduce this?  I'm working on similar problems right now but I want to make sure this is fixed.

**Comment by wmertens** [comment]
Well not at my computer right now but if you come the revealjs repo you can
just view the index.html in it and navigate through, that should update the
URL...

**Comment by wmertens** [comment]
Clone not come <sigh>

**Comment by mark-hahn** [comment]
> because if you reload it switches back to the beginning.

Did you mean auto-reload or just clicking on the reload button?

BTW, thanks mucho for your help.

**Comment by wmertens** [comment]
Ok, I tested it some more and the URL does change internally and plain reload does stay on the same URL, but only for http:// URLs :cry:.
So if you go to http://lab.hakim.se/reveal-js/#/1 and go to another page, the URL in the bar won't change but when manually reloading it does reload the URL correctly. Auto-reload loads the original URL, as you intended. So there the issue is only that the address doesn't get updated.

When you use a local copy of https://github.com/hakimel/reveal.js and therefore a file:// url, it doesn't seem to work that way. Manual reload goes back to the original URL.

...and thank *you* for making awesome plugins! :grin:

**Comment by mark-hahn** [comment]
> the issue is only that the address doesn't get updated.

This has been fixed in 1.3.0.  Thanks.
