### ISSUE TITLE
 Crashing when executing javascript script packages

### ISSUE THREAD

**Issue by Clovis2** [mark-hahn/web-browser#37]
I try to run an HTML file (which works fine on my browsers). This file execute a javascript script. The file is on my own file system on my computer.
Mac OS 10.9
Atom 0.182

**Comment by mark-hahn** [comment]
Executing a simple Hello Word javascript local file works for me.

Can you please send me a copy of the html and javascript files so I can try them? My email is mark@hahnca.com.

Thanks.

**Comment by mark-hahn** [comment]
I saw the same problem on my system.  It is a crash inside the webview html tag.  I posted an issue on atom/shell.  https://github.com/atom/atom-shell/issues/1198

**Comment by mark-hahn** [comment]
This web-browser package is no longer supported.  Use the atom package browser-plus instead.
