### ISSUE TITLE
Use the `atom-pane` tag instead of the `pane` class.

### ISSUE THREAD

**Issue by c-benko** [mark-hahn/web-browser#39]
The Deprecator Cop was throwing a warning. The simple fix is below.

In keymaps/web-browser.cson: Use the `atom-pane` tag instead of the `pane` class.

Amending the code in the `web-browser.cson` file to
```
'body .pane .item-views .browser-page webview':
  'tab':       'native!'
  'shift-tab': 'native!'
  'f12': 'web-browser:toggle-dev'
```

to 

```
'body atom-pane .item-views .browser-page webview':
  'tab':       'native!'
  'shift-tab': 'native!'
  'f12': 'web-browser:toggle-dev'
```

solved the Deprecation Cop warning.

**Comment by mark-hahn** [comment]
Thanks very much for your help and giving me the code.

Fixed in 1.4.2
