### ISSUE TITLE
live reload

### ISSUE THREAD

**Issue by ccorcos** [mark-hahn/web-browser#4]
Any way to get this browser to live reload my code?

**Comment by Ajedi32** [comment]
:+1: This would make this plugin perfect for previewing HTML. I haven't been able to find a decent plugin to do that yet which works.

**Comment by mark-hahn** [comment]
A major new version will be out in a week or two that can do this.

**Comment by Ajedi32** [comment]
Awesome! Thanks for letting me know.

**Comment by mark-hahn** [comment]
It didn't make it into 1.0.0 but I', starting on 1.1.0 which will have live-reload.

**Comment by mark-hahn** [comment]
1.1.2 was just released with an auto-reload feature.  This is a very simple no-configuration-required version of reload. You mark which webpage you want to auto-reload with a click in the toolbar. Then whenever any source file in the editor is saved that marked page will reload. You can specify a delay to give time for background processing, like a coffeescript compile, to complete.  The updated readme is at https://atom.io/packages/web-browser.

If anyone has a live-reload requirement that this doesn't work for let me know.

**Comment by Ajedi32** [comment]
Seems like a reasonable implementation. I can't get it to work for me though (see #28).

**Comment by Ajedi32** [comment]
Well, I finally got this to work. There's still a bug when using it with local pages (see #31) but it seems to work fine with pages on the web.
