### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by c-benko** [mark-hahn/web-browser#40]
The Deprecator Cop was throwing a warning. 

In keymaps/web-browser.cson: Use the `atom-text-editor` tag instead of the `editor` class.

Amending the code in the `web-browser.cson` file to
```
'.editor':
  'ctrl-h': 'web-browser:google-it'
  'ctrl-alt-h': 'web-browser:devdocs-it'
```

to 

```
'atom-text-editor':
  'ctrl-h': 'web-browser:google-it'
  'ctrl-alt-h': 'web-browser:devdocs-it'

```

solved the Deprecation Cop warning.

**Comment by mark-hahn** [comment]
Thanks very much for your help and giving me the code.

Fixed in 1.4.2
