### ISSUE TITLE
Conflicting keybindings for IPython/Jupyter

### ISSUE THREAD

**Issue by drewfustin** [mark-hahn/web-browser#41]
Default hotkey to (e.g.) delete a frame in IPython Notebook is esc-d (escape to access the menu, d for the command). For Notebooks opened in Atom with the web-browser package, the esc acts as an Atom cancel command rather than accessing the Notebook menu, and thus it's impossible for Notebook hotkeys to work. 

Thanks in advance!

Atom Version: 0.186.0
System: Mac OS X 10.10.2
Thrown From: web-browser package, v1.4.0

**Comment by mark-hahn** [comment]
This web-browser package is no longer supported.  Use the atom package browser-plus instead.
