### ISSUE TITLE
Refresh Page Command

### ISSUE THREAD

**Issue by Aarilight** [mark-hahn/web-browser#44]
It'd be nice for a 'Web Browser: Refresh Current Page' command to be added, so that I could bind refreshing the page to F5 rather than using the mouse to click the button. (With it back and forward would probably be handy to have as well)

Let me know if I'm an idiot and this already exists.

**Comment by mark-hahn** [comment]
> Let me know if I'm an idiot and this already exists.

I don't know if you are an idiot (grin) but it doesn't exist.  I haven't
added any keys to the page yet.  Most keys are built in to the webview tag.

I'll put it high on my to-do list.

**Comment by mark-hahn** [comment]
This web-browser package is no longer supported.  Use the atom package browser-plus instead.
