### ISSUE TITLE
Crashing every site i tried , atom.io ., google.com , yahoo.com.. nothing works.

### ISSUE THREAD

**Issue by v3ss0n** [mark-hahn/web-browser#46]
It crash wherever i go .

**Comment by Aarilight** [comment]
This is caused by an incompatibility with the new version of Atom, unfortunately. Hoping it gets fixed soon!

**Comment by mark-hahn** [comment]
Ouch.  Will fix this asap. I haven't kept my version up-to-date because my
auto-update never works.

On Sun, Apr 5, 2015 at 12:15 PM, Mackenzie McClane <notifications@github.com

**Comment by v3ss0n** [comment]
Thanks a lot. I am using atom-browser-webview now. It works . But same duplicated features on both project. Shouldn't two merged?

**Comment by mark-hahn** [comment]
I wanted to merge them and he agreed and then I never heard from him.  He's
also been a bit of a dick.  It's a long story.

**Comment by v3ss0n** [comment]
I just realized it was forked from you.

**Comment by mark-hahn** [comment]
This is fixed in 1.4.3

**Comment by v3ss0n** [comment]
Thanks , going to test soon.
