### ISSUE TITLE
Enter credentials to view pages with permissions

### ISSUE THREAD

**Issue by acoffin** [mark-hahn/web-browser#49]
I do a lot of development on a password protected directory on a live server. To view pages in this directory I need to enter my login credentials. I'd love to view these pages with web-browser, but I get no option to enter credentials. Instead I get:

"You do not have permission to view this directory or page."

**Comment by mark-hahn** [comment]
Thanks for the report.  There is a good chance this is a problem in the
html webview tag.  If so it would need to be reported on atom/atom-shell.
If you can figure out a way for me to repeat the problem I would be happy
to look at it and then post the issue there for you.

**Comment by acoffin** [comment]
Awesome, thanks!

You should see the issue if you try to visit [http://synapsory.com/dev/](http://synapsory.com/dev/) using web-browser in atom.

**Comment by mark-hahn** [comment]
I saw the problem.  There was already an issue on atom/atom-shell.  https://github.com/atom/atom-shell/issues/1362

**Comment by acoffin** [comment]
Thanks for passing it along. Hopefully there's a solution soon.

**Comment by mark-hahn** [comment]
That issue was only created 10 days ago.  A bit of a coincidence.  I doubt
any fix would get through the pipeline in less than a month.  Talk the
owner of the server into switching to a modern authentication scheme.  :-)

**Comment by acoffin** [comment]
That was an alternate server I was trying to debug the problem with. The actual server that's giving me issues uses webDAV and a single sign-on system that works with the campus network. Same problem though.

**Comment by mark-hahn** [comment]
I'm sorry about that.  As the other guy said, there is no work-around.

**Comment by acoffin** [comment]
No worries. Hopefully it'll be fixed in a future atom update. Thanks for your help.
