### ISSUE TITLE
SAMEORIGIN display error

### ISSUE THREAD

**Issue by puup** [mark-hahn/web-browser#5]
Refused to display 'https://www.google.com/?gws_rd=ssl' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by DinisCruz** [comment]
I just had the same issue trying to open GitHub

![image](https://cloud.githubusercontent.com/assets/656739/5680662/4ca6804c-9808-11e4-9e46-a7d0a654c1ac.png)

**Comment by mark-hahn** [comment]
There is a fix for this.  @gstack forked web-browser and published
https://atom.io/packages/atom-browser-webview.  It has a "fix" for the
chrome webview bug.  He is going to push the change to web-browser but for
now you can use his package.

On related news google has issued a webview bug fix.  If it is the one that
is clobbering web-browser then we should have a simpler and maybe more
robust fix.

**Comment by mark-hahn** [comment]
@gstack mentioned that atom-browser-webview
<https://atom.io/packages/atom-browser-webview> isn't quite ready for
production.

**Comment by DinisCruz** [comment]
For reference that trick solves it, here is GitHub running inside Atom

![image](https://cloud.githubusercontent.com/assets/656739/5690821/5ec481ee-989d-11e4-80da-57bf1a5bb6ec.png)

**Comment by mark-hahn** [comment]
Closing in favor of #6

**Comment by mark-hahn** [comment]
Good news.  The webview element is now fixed in Atom.  I should have a new fully-working version of `web-browser` with new features in a week or so.

**Comment by mark-hahn** [comment]
fixed in 1.0.0

**Comment by vamsipriyamaddipatla** [comment]
I have been trying to display one URL in IFrames. In IE it is displaying "This content cannot be displayed in a frame" error. Could you please tell me how to fix this issue??

**Comment by mark-hahn** [comment]
I'm sorry but I don't know anything that can help you.  I don't remember
anything related to iFrames.  I ended up using webview elements, not
iframes.
