### ISSUE TITLE
Opening Local HTMLS

### ISSUE THREAD

**Issue by diggetybo** [mark-hahn/web-browser#51]
Hey,

Your package is great. For some reason I cannot view htmls on my computer though. When I copy and paste a local file path of an html, the package overwrites the C:/ to html:// everytime. or rather, it inserts html:// before the c:/, which of course loads a blank page.

Is there someway to get around this? Please advise.

Thanks,

Zac

**Comment by mark-hahn** [comment]
I'm sorry but the package `Web-Browser` has been deprecated in favor of the package `Browser-Plus`.  I should make the notice bigger.

**Comment by diggetybo** [comment]
Oh, I see. I will take note of that, thanks for the reply.
